### ISSUE TITLE
Problems of timeout

### ISSUE THREAD

**Issue by PhilippeR26** [0xSpaceShard/starknet-devnet-js#5]
By default a Devnet-Provider has a timeout of 10s.
On my infra, I recorded an average duration of 7 seconds to flush one message L2->L1.
So, my script fails if I have more than one message to send to L1.
Even if it can be customized at `DevnetProvider` class instantiation, I think that the default timeout should be increased to something like 25-30s.

**Comment by FabijanC** [comment]
Fixed in https://github.com/0xSpaceShard/starknet-devnet-js/pull/4
