### ISSUE TITLE
option of .flush() is not intuitive

### ISSUE THREAD

**Issue by PhilippeR26** [0xSpaceShard/starknet-devnet-js#6]
`myDevnetProvider.flush(true)` has to be written ... to not perform the flush! It is not really intuitive.

My proposal :
- `.flush()` or `.flush({dryRun: false})`  to perform the flush
- `.flush({dryRun: true})` to not perform it. 

Seems much more intuitive.

**Comment by FabijanC** [comment]
Fixed in 9380c672f0bc2701957daa0eee46e9542e1a3985 and d078879f6aeab22b5430bea50fa7adc72ca1f00c.
